### ISSUE TITLE
process.env.BEARCAT_LOGGER关闭是否会导致内存泄漏？

### ISSUE THREAD

**Issue by zj8487** [bearcatjs/bearcat#123]
@fantasyni 
如果我将process.env.BEARCAT_LOGGER关闭。
并且在项目的log4j.json中不配置bearcat日志项
那么会导致bearcat的日志记录内存泄漏吗？

**Comment by fantasyni** [comment]
不会的，都是同一个 pomelo-logger ，不配置就是不配置对应的 category 日志不会输出到对应的 file/console 而已，忽略了

**Comment by zj8487** [comment]
okay,好的。

但是：都是同一个 pomelo-logger 这个可能不正确。

今天刚填了个坑：在pomelo中使用bearcat，如果不关闭bearcat的日志，会导致日志异常。
http://nodejs.netease.com/topic/548d24c3cb93b0031fb1918e
