### ISSUE TITLE
Autowiring of module $async fails

### ISSUE THREAD

**Issue by ahmedghoneim92** [bearcatjs/bearcat#124]
If you name a module with this.$id = 'async' and try to autowire it in any other module with this.$async = null it remains null.

**Comment by fantasyni** [comment]
$async has special meanings, it can not be used as a bean id  
[Configuration attribute](http://bearcatjs.org/guide/magic-javaScript-objects-in-details.html#Configuration_attribute)  
async : specify whether the init method is async or not, by default it is false

**Comment by fantasyni** [comment]
better warn log notification is needed, added it to the bearcat roadmap
