### ISSUE TITLE
Project is dead? Could you recommend some alternatives, please, thx!

### ISSUE THREAD

**Issue by moredure** [bearcatjs/bearcat#224]

**Comment by juicetin** [comment]
I came across this recently:
https://github.com/young-steveo/bottlejs/

It's an alternative that's being actively developed on - it's not a complete feature match though, and actually as of right now I think bearcat may be the slightly 'easier' one to use (speaking from the perspective of also having used bearcat before). It looks promising and just started using it myself though!
