### ISSUE TITLE
有没有考虑前端代码也用这个

### ISSUE THREAD

**Issue by dogagithub** [bearcatjs/bearcat#87]
前端的包管理也已经非常舒服了：https://github.com/duojs/duo
不知道bearcat有没有考虑让前端也能够使用，这样某些前后端代码就能通用了

**Comment by zj8487** [comment]
@fantasyni 
这个只能在浏览器环境用吗？
能否在cocos2d-jsb和cocos2d-html5中使用？

**Comment by fantasyni** [comment]
@zj8487 
他们两个有自己 require 机制，需要调研一下，主要是 js 本身没有统一的模块机制（es6 才有），都是上层自己实现的，比较坑

**Comment by zj8487** [comment]
@fantasyni 
我后端全用的bearcat，非常舒服。
非常希望前端也用。
我构想了下，如果能用的话。前端就比我现在的舒服太多了。
感谢你的工作哈。

**Comment by fantasyni** [comment]
@zj8487 
加入bearcat的roadmap里面了哈

**Comment by zj8487** [comment]
@fantasyni 
多谢，但是量力而为吧。我想了下。很多坑啊。

**Comment by fantasyni** [comment]
@zj8487 
理论上，bearcat可以使用在所有js环境中的，哈哈

**Comment by zj8487** [comment]
@fantasyni 
cocos2d-jsb有个自动更新功能，如果用bearcat，文件的目录固定了，就不能获取新文件了。

所以可能不行

**Comment by fantasyni** [comment]
@zj8487 
文件也可以动态加的啊  
```
bearcat.module()
```

支持bearcat启动后再加入的
